defaults:
  - default
  - _self_

model:
  name: grin
  hparams:
    hidden_size: 64
    ff_size: 64
    embedding_size: 8
    n_layers: 1
    kernel_size: 2
    decoder_order: 1
    layer_norm: False
    dropout: 0
    ff_dropout: 0
    merge_mode: 'mlp'
