defaults:
  - default
  - _self_

model:
  name: rnni
  hparams:
    hidden_size: 64
    cell: 'gru'
    concat_mask: True
    detach_input: False
    fully_connected: True
    n_layers: 1
    cat_states_layers: False
