# @package _global_

#### Model params #############################################################
model:
  name: transformer
  hparams:
    hidden_size: 64
    ff_size: 128
    n_layers: 4
    n_heads: 2
    dropout: 0.1
    axis: both

#### Config overrides #########################################################
optimizer:
  hparams:
    lr: 0.001
